#include "audio.hpp"
#include "track.hpp"

static bool EVENT_TYPE()
{
	AUDIO_EVENT::IS_VIDEO || AUDIO_EVENT::IS_AUDIO;
	return;
}

static bool OPERATION()
{
	AUDIO_OPERATION::EQUAL;
	AUDIO_OPERATION::NOT_EQ_TO;
	return;
}

static const double NORMALISE_GAIN()
{
	AUDIO_EVENT::RESULT = false;
	AUDIO_EVENT::GET_NORMALISE = TRACK_EVENT::TRACK_ID, TRACK_EVENT::EVENT_ID;
	return AUDIO_EVENT::RESULT;
	AUDIO_EVENT::SET_NORM = TRACK_EVENT::TRACK_ID, TRACK_EVENT::EVENT_ID, AUDIO_GAIN::NORM, NULL, 1.0;
}
